HOMEWORK2-DL w/ Pytorch

In [6]:
#required imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

#Tensor operations
my_first_tensor = torch.rand(5,5)
tensor_size=my_first_tensor.shape
print(tensor_size,'\n', my_first_tensor)

identity_tensor=torch.eye(5)
print(identity_tensor)

print(torch.matmul(my_first_tensor,identity_tensor))
print(my_first_tensor*identity_tensor)

#With a element wise multiplication we get the correct 
#solution when multiplied with an identity matrix, whereas with matmul
#i get my_first_tensor as a solution.

torch.Size([5, 5]) 
 tensor([[0.6480, 0.1362, 0.7373, 0.6902, 0.9998],
        [0.5795, 0.1643, 0.0528, 0.0666, 0.7562],
        [0.5302, 0.7486, 0.4450, 0.1623, 0.5030],
        [0.4426, 0.5007, 0.9681, 0.1803, 0.3591],
        [0.9911, 0.8102, 0.3038, 0.2114, 0.0920]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[0.6480, 0.1362, 0.7373, 0.6902, 0.9998],
        [0.5795, 0.1643, 0.0528, 0.0666, 0.7562],
        [0.5302, 0.7486, 0.4450, 0.1623, 0.5030],
        [0.4426, 0.5007, 0.9681, 0.1803, 0.3591],
        [0.9911, 0.8102, 0.3038, 0.2114, 0.0920]])
tensor([[0.6480, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.1643, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.4450, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.1803, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0920]])


Your first neural networks

In [7]:
#9)
pixels=265*265
print('Amount of pixels =',pixels)

input_layer=torch.rand(1, pixels)
print(input_layer)
#10)
weight_1 = torch.rand(70225, 200)
weight_2 = torch.rand(200, 10)




Amount of pixels = 70225
tensor([[0.0248, 0.3043, 0.8011,  ..., 0.8165, 0.1619, 0.8063]])


11) Set the result of input_layer times weight_1 to hidden_1.
12) Set the result of hidden_1 times weight_2 to output_layer and print the output_layer.
Are 10 classes identified?

In [8]:
hidden_1 = torch.matmul(input_layer, weight_1)
output_layer = torch.matmul(hidden_1, weight_2)
print("The output values are:", output_layer)
print("The size of the output values are:", output_layer.shape)

The output values are: tensor([[1811371.3750, 1737376.7500, 1895259.1250, 1915615.3750, 1733174.3750,
         1783890.0000, 1726234.5000, 1749033.7500, 1771906.2500, 1649291.0000]])
The size of the output values are: torch.Size([1, 10])


13) Build the same neural network from steps 9-12, but now the PyTorch way.
Create a class called Net with input nn.Module.
Import the required package.
14) Instantiate two linear layers calling them self.fc1 and self.fc2.
15) Implement the .forward() method, using the two layers you defined and returning x.
16) Now you have successfully built your first fully connected neural network!
What makes this network a fully connected one?

In [9]:
# Define the class called ANN which inherits from nn.Module# 


class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1=nn.Linear(1,70225)
        self.fc2=nn.Linear(70225,200)
        self.output=nn.Linear(200,10)

    def forward(self,x):
        x=F.relu(self.fc1(x))
        x=F.relu(self.fc2(x))
        x=self.output(x)
        return x


#They are fully connected because all nodes of the the input-, hidden-, output layer are connceted with each other and they get the input information, manipulate them 
#and pass them forward to the output